version: "3.9"
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge-decampoacampo
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
